name: Links (Fail Fast)

on:
    push:
      branches:
        - master  # Only runs on pushes to main branch
    pull_request:
      branches:
        - master  # Runs on pull requests targeting main branch

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.9.0
        with:
          fail: true