name: Markdown Lint and Auto-Fix

on:
    push:
      branches:
        - master  # Only runs on pushes to main branch
    pull_request:
      branches:
        - master  # Runs on pull requests targeting main branch
        
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run markdownlint-cli2 with auto-fix
        uses: DavidAnson/markdownlint-cli2-action@v17
        with:
          fix: true
          globs: '**/*.md'

      - name: Check if there are any changes
        id: changes
        run: |
          git add .
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
            echo "::set-output name=changes_made::false"
          else
            echo "Changes have been made"
            echo "::set-output name=changes_made::true"
          fi

      - name: Commit changes if any fixes were applied
        if: steps.changes.outputs.changes_made == 'true'
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git commit -m "chore: auto-fix markdown lint issues"

      - name: Push changes
        if: steps.changes.outputs.changes_made == 'true'
        run: git push origin HEAD:refs/heads/master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
