name: Markdown Lint and Auto-Fix

on:
    push:
      branches:
        - master  # Only runs on pushes to main branch
    pull_request:
      branches:
        - master  # Runs on pull requests targeting main branch

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run markdownlint-cli2 with auto-fix
        uses: DavidAnson/markdownlint-cli2-action@v17
        with:
          fix: true
          globs: '**/*.md'

      - name: Check if there are any changes
        id: changes
        run: |
          git add .
          if git diff-index --quiet HEAD --; then
            echo "changes_made=false" >> $GITHUB_OUTPUT
          else
            echo "changes_made=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit changes if any fixes were applied
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "chore: auto-fix markdown lint issues" || echo "No changes to commit"

      - name: Push changes
        if: success()
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
