name: Markdown Lint and Auto-Fix

on:
  push:
    branches:
      - main
      - '**'  # Lint on all branches
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run markdownlint-cli2 with auto-fix
        uses: DavidAnson/markdownlint-cli2-action@v17
        with:
          fix: true
          globs: '**/*.md'
